spring:
  # 日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 配置数据库连接
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/flower_shop_online?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 解决swagger报错
  mvc:
    pathmatch:
      matching-strategy:
        ANT_PATH_MATCHER

# tomcat配置
server:
  tomcat:
    uri-encoding: UTF-8 #解决乱码
  port: 8080 #默认端口

mybatis:
  # 加载mapper位置
  mapper-locations: classpath:mapper/*.xml
  # 别名设置
  type-aliases-package: com.example.mybatispustest.entity

mybatis-plus:
  global-config:
    # 配置逻辑删除字段
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0